# index:
#    path: /
#    controller: App\Controller\DefaultController::index

trans:
    path: /{_locale}/trans
    controller: App\Controller\TransController::index
    requirements:
        _locale: en_US|fr_FR|cs_CZ